// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD64L9Rp9Ti8qM1KLH4lXelFi1_um-GmmA',
    appId: '1:61144790479:android:6939d4b9508b1d0c3eceba',
    messagingSenderId: '61144790479',
    projectId: 'eclassify-8397f',
    storageBucket: 'eclassify-8397f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDnHXfZLpcm8KerimibUeM7h-IO7Ht6TQ',
    appId: '1:61144790479:ios:e75d14829c4536553eceba',
    messagingSenderId: '61144790479',
    projectId: 'eclassify-8397f',
    storageBucket: 'eclassify-8397f.firebasestorage.app',
    androidClientId:
        '61144790479-nq0melc0slo4o6j6avpbb957ngllfucq.apps.googleusercontent.com',
    iosClientId:
        '61144790479-igr6osg4pasoabu6i4so339abatd9ba1.apps.googleusercontent.com',
    iosBundleId: 'com.qemma.wazifati',
  );
}
